project:
  type: website
  output-dir: docs

website:
  title: "ashlesha.khatiwada"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research_site.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

